<?php
declare(strict_types=1);
function cms_seed_blocks(): array {
  return [
    // home — hero
    ['page_slug'=>'home','section_key'=>'hero','sort_order'=>0,'title_en'=>'Shree Public Secondary School — Malangwa-2','title_np'=>'श्री पब्लिक माध्यमिक विद्यालय — मलंगवा-२','subtitle_en'=>'Admissions Open 2082','subtitle_np'=>'भर्ना खुला २०८२','body_en'=>'Providing public education from Early Childhood Development through Grade 12 in the heart of Malangwa. ECD–12 • +2 Science & Management (NEB).','body_np'=>'मलंगवाको केन्द्रमा बालविकासदेखि कक्षा १२ सम्म सार्वजनिक शिक्षा। ईसीडी–१२ • +२ विज्ञान तथा व्यवस्थापन (एनईबी)।','image_url'=>'uploads/hero/hero-main-gate-jubilee.jpg','icon'=>null,'link_url'=>null,'is_active'=>1],
    // home — stat (4)
    ['page_slug'=>'home','section_key'=>'stat','sort_order'=>1,'title_en'=>'45+','title_np'=>'४५+','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Qualified Teachers','body_np'=>'योग्य शिक्षकहरू','image_url'=>null,'icon'=>'groups','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'home','section_key'=>'stat','sort_order'=>2,'title_en'=>'1,000+','title_np'=>'१,०००+','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Students','body_np'=>'विद्यार्थीहरू','image_url'=>null,'icon'=>'groups','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'home','section_key'=>'stat','sort_order'=>3,'title_en'=>'1947','title_np'=>'१९४७','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Established','body_np'=>'स्थापना','image_url'=>null,'icon'=>'history_edu','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'home','section_key'=>'stat','sort_order'=>4,'title_en'=>'98%','title_np'=>'९८%','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Pass Rate','body_np'=>'उत्तीर्ण दर','image_url'=>null,'icon'=>'verified','link_url'=>null,'is_active'=>1],
    // home — intro
    ['page_slug'=>'home','section_key'=>'intro','sort_order'=>0,'title_en'=>'About Our School','title_np'=>'हाम्रो विद्यालयको बारेमा','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Shree Public Secondary School is a government-recognised community educational institution situated in the heart of Malangwa Municipality-2, Sarlahi District, Madhesh Province. Registered under IEMIS Code 190640003, our school plays a central role in providing accessible education to the local community. We offer formal education from Early Childhood Development (ECD) up to Grade 12, following the National Examination Board (NEB) curriculum.','body_np'=>'श्री पब्लिक माध्यमिक विद्यालय मधेश प्रदेशको सर्लाही जिल्ला, मलंगवा नगरपालिका-२ को केन्द्रमा अवस्थित सरकारबाट मान्यता प्राप्त सामुदायिक शैक्षिक संस्था हो। IEMIS कोड १९०६४०००३ मा दर्ता भएको हाम्रो विद्यालयले स्थानीय समुदायलाई पहुँचयोग्य शिक्षा प्रदान गर्न केन्द्रीय भूमिका खेल्दछ। हामी प्रारम्भिक बालविकास (ईसीडी) देखि कक्षा १२ सम्म राष्ट्रिय परीक्षा बोर्ड (एनईबी) को पाठ्यक्रम अनुसार औपचारिक शिक्षा प्रदान गर्छौं।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // home — commitment (4)
    ['page_slug'=>'home','section_key'=>'commitment','sort_order'=>1,'title_en'=>'National Curriculum','title_np'=>'राष्ट्रिय पाठ्यक्रम','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Curriculum per Curriculum Development Centre (CDC).','body_np'=>'पाठ्यक्रम विकास केन्द्र (सीडीसी) अनुसारको पाठ्यक्रम।','image_url'=>null,'icon'=>'volunteer_activism','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'home','section_key'=>'commitment','sort_order'=>2,'title_en'=>'Two NEB Streams','title_np'=>'दुई एनईबी स्ट्रिमहरू','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'+2 Science & Management under NEB.','body_np'=>'एनईबी अन्तर्गत +२ विज्ञान र व्यवस्थापन।','image_url'=>null,'icon'=>'workspace_premium','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'home','section_key'=>'commitment','sort_order'=>3,'title_en'=>'Community Focus','title_np'=>'सामुदायिक केन्द्रित','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Serving families of Malangwa-2 and surrounding wards.','body_np'=>'मलंगवा-२ र वरपरका वडाका परिवारहरूको सेवा।','image_url'=>null,'icon'=>'biotech','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'home','section_key'=>'commitment','sort_order'=>4,'title_en'=>'Government Oversight','title_np'=>'सरकारी रेखदेख','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Public community school — IEMIS 190640003.','body_np'=>'सामुदायिक विद्यालय — IEMIS १९०६४०००३।','image_url'=>null,'icon'=>'handshake','link_url'=>null,'is_active'=>1],
    // home — cta_banner
    ['page_slug'=>'home','section_key'=>'cta_banner','sort_order'=>0,'title_en'=>'Admissions Now Open for 2082','title_np'=>'२०८२ का लागि भर्ना खुला छ','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Secure a bright future. Join Shree Public Secondary School today.','body_np'=>'उज्ज्वल भविष्य सुनिश्चित गर्नुहोस्। आजै श्री पब्लिक माध्यमिक विद्यालयमा सामेल हुनुहोस्।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // about — page_header
    ['page_slug'=>'about','section_key'=>'page_header','sort_order'=>0,'title_en'=>'About Our School','title_np'=>'हाम्रो विद्यालयको बारेमा','subtitle_en'=>'Malangwa-2, Sarlahi','subtitle_np'=>'मलंगवा-२, सर्लाही','body_en'=>null,'body_np'=>null,'image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // about — intro (2)
    ['page_slug'=>'about','section_key'=>'intro','sort_order'=>1,'title_en'=>'A Pillar of Community Education','title_np'=>'सामुदायिक शिक्षाको आधार','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Shree Public Secondary School stands at the heart of Malangwa as a cornerstone of government-led education in Madhesh Province. As a public community school, we are dedicated to providing accessible, high-quality education to over 1,000 students.','body_np'=>'श्री पब्लिक माध्यमिक विद्यालय मधेश प्रदेशमा सरकारी शिक्षाको आधारशिलाको रूपमा मलंगवाको केन्द्रमा खडा छ। एक सार्वजनिक सामुदायिक विद्यालयको रूपमा, हामी १,००० भन्दा बढी विद्यार्थीहरूलाई पहुँचयोग्य, गुणस्तरीय शिक्षा प्रदान गर्न समर्पित छौं।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'intro','sort_order'=>2,'title_en'=>null,'title_np'=>null,'subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Our institution offers a comprehensive educational journey from Early Childhood Development (ECD) through Grade 12. We proudly operate as a co-educational day school, fostering an inclusive environment. In our higher secondary levels (+2), we provide specialized streams in Science and Management, equipping our students with the skills necessary for modern professional landscapes. (IEMIS: 190640003)','body_np'=>'हाम्रो संस्थाले प्रारम्भिक बालविकास (ईसीडी) देखि कक्षा १२ सम्म व्यापक शैक्षिक यात्रा प्रदान गर्दछ। हामी सह-शिक्षा दिवा विद्यालयको रूपमा समावेशी वातावरण प्रवर्द्धन गर्छौं। उच्च माध्यमिक तह (+२) मा हामी विज्ञान र व्यवस्थापनका विशेषीकृत स्ट्रिमहरू प्रदान गर्छौं। (IEMIS: १९०६४०००३)','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // about — value (3)
    ['page_slug'=>'about','section_key'=>'value','sort_order'=>1,'title_en'=>'Vision','title_np'=>'परिकल्पना','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'To be a leading center of educational excellence in Madhesh Province, empowering students with knowledge, skills, and values for a global future.','body_np'=>'मधेश प्रदेशमा शैक्षिक उत्कृष्टताको अग्रणी केन्द्र बन्ने, विद्यार्थीहरूलाई वैश्विक भविष्यका लागि ज्ञान, सीप र मूल्यहरूद्वारा सशक्त बनाउने।','image_url'=>null,'icon'=>'visibility','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'value','sort_order'=>2,'title_en'=>'Mission','title_np'=>'लक्ष्य','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Providing accessible, high-quality public education from ECD to Grade 12, fostering an inclusive environment that nurtures intellectual growth and civic responsibility.','body_np'=>'ईसीडीदेखि कक्षा १२ सम्म पहुँचयोग्य, उच्च गुणस्तरीय सार्वजनिक शिक्षा प्रदान गर्ने, बौद्धिक वृद्धि र नागरिक जिम्मेवारीलाई पोषण गर्ने समावेशी वातावरण निर्माण गर्ने।','image_url'=>null,'icon'=>'school','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'value','sort_order'=>3,'title_en'=>'Values','title_np'=>'मूल्यहरू','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Integrity, Inclusivity, Excellence, and Community Trust.','body_np'=>'इमानदारी, समावेशिता, उत्कृष्टता र सामुदायिक विश्वास।','image_url'=>null,'icon'=>'workspace_premium','link_url'=>null,'is_active'=>1],
    // about — timeline (4)
    ['page_slug'=>'about','section_key'=>'timeline','sort_order'=>1,'title_en'=>'2003 BS','title_np'=>'२००३ साल','subtitle_en'=>'1947 AD','subtitle_np'=>'सन् १९४७','body_en'=>'Establishment of the school as a primary education center.','body_np'=>'प्राथमिक शिक्षा केन्द्रको रूपमा विद्यालयको स्थापना।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'timeline','sort_order'=>2,'title_en'=>'2040 BS','title_np'=>'२०४० साल','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Expansion to secondary level (Grade 10).','body_np'=>'माध्यमिक तह (कक्षा १०) सम्म विस्तार।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'timeline','sort_order'=>3,'title_en'=>'2065 BS','title_np'=>'२०६५ साल','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Introduction of Higher Secondary (+2) programs.','body_np'=>'उच्च माध्यमिक (+२) कार्यक्रमहरूको सुरुवात।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'timeline','sort_order'=>4,'title_en'=>'2080 BS','title_np'=>'२०८० साल','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Modernization with ICT-integrated Smart Classrooms.','body_np'=>'आईसीटी एकीकृत स्मार्ट कक्षाहरू सहित आधुनिकीकरण।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // about — facility (4)
    ['page_slug'=>'about','section_key'=>'facility','sort_order'=>1,'title_en'=>'Science Laboratory','title_np'=>'विज्ञान प्रयोगशाला','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Well-equipped for Physics, Chemistry, and Biology experiments.','body_np'=>'भौतिक विज्ञान, रसायन विज्ञान र जीव विज्ञान प्रयोगका लागि सुसज्जित।','image_url'=>'uploads/gallery/campus/staff-room-interior.jpg','icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'facility','sort_order'=>2,'title_en'=>'ICT Lab','title_np'=>'आईसीटी ल्याब','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Modern computer lab with internet access for smart learning.','body_np'=>'स्मार्ट लर्निङका लागि इन्टरनेट सहितको आधुनिक कम्प्युटर ल्याब।','image_url'=>'uploads/gallery/campus/staff-room-computer.jpg','icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'facility','sort_order'=>3,'title_en'=>'Library','title_np'=>'पुस्तकालय','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'A collection of academic and reference books for all levels.','body_np'=>'सबै तहका लागि शैक्षिक र सन्दर्भ पुस्तकहरूको संग्रह।','image_url'=>'uploads/gallery/campus/headmaster-office.jpg','icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'about','section_key'=>'facility','sort_order'=>4,'title_en'=>'Sports Ground','title_np'=>'खेल मैदान','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Space for athletics, football, and community events.','body_np'=>'एथलेटिक्स, फुटबल र सामुदायिक कार्यक्रमहरूका लागि ठाउँ।','image_url'=>'uploads/gallery/campus/courtyard-students-formation.jpg','icon'=>null,'link_url'=>null,'is_active'=>1],
    // about — cta_join
    ['page_slug'=>'about','section_key'=>'cta_join','sort_order'=>0,'title_en'=>'Join Our Community','title_np'=>'हाम्रो समुदायमा सामेल हुनुहोस्','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Explore our academic programs or start the admission process today to become part of Shree Public Secondary School.','body_np'=>'हाम्रा शैक्षिक कार्यक्रमहरू अन्वेषण गर्नुहोस् वा आजै श्री पब्लिक माध्यमिक विद्यालयको हिस्सा बन्न भर्ना प्रक्रिया सुरु गर्नुहोस्।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // faq — faq_item (9)
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>1,'title_en'=>'Where is the school located?','title_np'=>'विद्यालय कहाँ अवस्थित छ?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p><strong>Shree Public Secondary School</strong> (श्री पब्लिक माध्यमिक विद्यालय) is in <strong>Malangwa Municipality-2, Sarlahi, Madhesh Province 45800, Nepal</strong>. Plus Code <strong>VH24+22W</strong> (26.8501032 N, 85.555064 E). See <a href="/contact.php">Contact — Map &amp; directions</a> for the embedded map and directions link.</p>','body_np'=>'<p><strong>श्री पब्लिक माध्यमिक विद्यालय</strong> <strong>मलंगवा नगरपालिका-२, सर्लाही, मधेश प्रदेश ४५८००, नेपाल</strong> मा अवस्थित छ। प्लस कोड <strong>VH24+22W</strong> (२६.८५०१०३२ N, ८५.५५५०६४ E)। नक्सा र दिशा-निर्देशका लागि <a href="/contact.php">सम्पर्क — नक्सा र दिशा</a> हेर्नुहोस्।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>2,'title_en'=>'What levels does the school teach?','title_np'=>'विद्यालयले कुन तहसम्म पढाउँछ?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>The school covers <strong>ECD through Grade 12</strong> on a single campus — ECD / Nursery, Basic Level (Grades 1–8), Secondary Level (Grades 9–10, SEE) and Higher Secondary (Grades 11–12, NEB). See <a href="/academics.php">Academics</a> for a detailed explanation of each level.</p>','body_np'=>'<p>विद्यालयले <strong>ईसीडीदेखि कक्षा १२ सम्म</strong> एउटै परिसरमा पढाउँछ — ईसीडी/नर्सरी, आधारभूत तह (कक्षा १–८), माध्यमिक तह (कक्षा ९–१०, एसईई) र उच्च माध्यमिक (कक्षा ११–१२, एनईबी)। प्रत्येक तहको विस्तृत विवरणका लागि <a href="/academics.php">शैक्षिक कार्यक्रम</a> हेर्नुहोस्।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>3,'title_en'=>'Which +2 programs are available?','title_np'=>'कुन +२ कार्यक्रमहरू उपलब्ध छन्?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>Currently <strong>+2 Science</strong> and <strong>+2 Management</strong> under the National Examinations Board (NEB). Program descriptions are on <a href="/science.php">+2 Science</a> and <a href="/management.php">+2 Management</a>. Exact subject combinations for the current year are confirmed by the school office.</p>','body_np'=>'<p>हाल <strong>+२ विज्ञान</strong> र <strong>+२ व्यवस्थापन</strong> राष्ट्रिय परीक्षा बोर्ड (एनईबी) अन्तर्गत सञ्चालित छन्। कार्यक्रम विवरण <a href="/science.php">+२ विज्ञान</a> र <a href="/management.php">+२ व्यवस्थापन</a> मा हेर्न सकिन्छ। चालु वर्षको विषय संयोजन विद्यालय कार्यालयले पुष्टि गर्दछ।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>4,'title_en'=>'Where are official notices published?','title_np'=>'आधिकारिक सूचनाहरू कहाँ प्रकाशित हुन्छन्?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>All official notices are published on the <a href="/notices.php">Notice Board</a>. Pinned / urgent notices appear first. For admission specifically, use <a href="/notices.php?category=admission">Notice Board — Admission</a>.</p>','body_np'=>'<p>सबै आधिकारिक सूचनाहरू <a href="/notices.php">सूचना पाटी</a> मा प्रकाशित हुन्छन्। पिन गरिएका/जरुरी सूचनाहरू पहिले देखिन्छन्। भर्नाका लागि <a href="/notices.php?category=admission">सूचना पाटी — भर्ना</a> हेर्नुहोस्।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>5,'title_en'=>'Where can I download forms and school documents?','title_np'=>'फारम र विद्यालयका कागजातहरू कहाँ डाउनलोड गर्न सकिन्छ?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>In the <a href="/downloads.php">Downloads / Resources centre</a> — categories include Academic Calendar, Exam Routine, Admission Documents, Results, Forms, Policies, Citizen Charter and Publications.</p>','body_np'=>'<p><a href="/downloads.php">डाउनलोड / संसाधन केन्द्र</a> मा — शैक्षिक पात्रो, परीक्षा तालिका, भर्ना कागजात, नतिजा, फारम, नीति, नागरिक वडापत्र र प्रकाशनहरू समावेश छन्।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>6,'title_en'=>'How can I get directions to the school?','title_np'=>'विद्यालयसम्म कसरी पुग्ने?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>Use the embedded map and <strong>Get Directions — VH24+22W</strong> button on the <a href="/contact.php">Contact page</a>, or search Plus Code <strong>VH24+22W</strong> / coordinates <strong>26.8501032, 85.555064</strong> in Google Maps.</p>','body_np'=>'<p><a href="/contact.php">सम्पर्क पृष्ठ</a> मा रहेको नक्सा र <strong>दिशा प्राप्त गर्नुहोस् — VH24+22W</strong> बटन प्रयोग गर्नुहोस्, वा Google Maps मा प्लस कोड <strong>VH24+22W</strong> / निर्देशांक <strong>२६.८५०१०३२, ८५.५५५०६४</strong> खोज्नुहोस्।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>7,'title_en'=>'How do I confirm admission requirements?','title_np'=>'भर्ना आवश्यकताहरू कसरी पुष्टि गर्ने?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>Check the <a href="/notices.php?category=admission">latest admission notice</a> for the grade and year you are applying for, and <a href="/contact.php">contact or visit the school</a> to confirm eligibility, seats, fees and deadline. The general guidance on the <a href="/admissions.php">Admissions page</a> is not a substitute for the official notice.</p>','body_np'=>'<p>तपाईंले आवेदन दिने कक्षा र वर्षका लागि <a href="/notices.php?category=admission">नवीनतम भर्ना सूचना</a> जाँच गर्नुहोस् र योग्यता, सिट, शुल्क र अन्तिम मिति पुष्टि गर्न <a href="/contact.php">विद्यालयमा सम्पर्क गर्नुहोस् वा भ्रमण गर्नुहोस्</a>। <a href="/admissions.php">भर्ना पृष्ठ</a> मा रहेको सामान्य मार्गदर्शन आधिकारिक सूचनाको विकल्प होइन।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>8,'title_en'=>'Are examination results available online?','title_np'=>'परीक्षा नतिजा अनलाइन उपलब्ध छन्?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>Published online results appear in <a href="/results.php">Results</a> (search by symbol / roll number) and as downloadable PDFs in <a href="/downloads.php">Downloads</a>. Board results for Grade 12 are also verifiable via <a href="https://neb.gov.np" target="_blank" rel="noopener">neb.gov.np</a>.</p>','body_np'=>'<p>प्रकाशित अनलाइन नतिजाहरू <a href="/results.php">नतिजा</a> (सिम्बोल नम्बरबाट खोज्नुहोस्) र <a href="/downloads.php">डाउनलोड</a> मा PDF को रूपमा उपलब्ध हुन्छन्। कक्षा १२ को बोर्ड नतिजा <a href="https://neb.gov.np" target="_blank" rel="noopener">neb.gov.np</a> मा पनि प्रमाणित गर्न सकिन्छ।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    ['page_slug'=>'faq','section_key'=>'faq_item','sort_order'=>9,'title_en'=>'What does IEMIS 190640003 mean?','title_np'=>'IEMIS १९०६४०००३ को अर्थ के हो?','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>It is the <strong>Integrated Educational Management Information System</strong> code identifying Shree Public Secondary School as a public institution within Nepal\'s education data system (CEHRD).</p>','body_np'=>'<p>यो <strong>एकीकृत शैक्षिक व्यवस्थापन सूचना प्रणाली</strong> कोड हो जसले श्री पब्लिक माध्यमिक विद्यालयलाई नेपालको शिक्षा तथ्यांक प्रणाली (CEHRD) भित्र सार्वजनिक संस्थाको रूपमा पहिचान गर्दछ।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // links — link (8)
    ['page_slug'=>'links','section_key'=>'link','sort_order'=>1,'title_en'=>'Ministry of Education, Science & Technology','title_np'=>'शिक्षा, विज्ञान तथा प्रविधि मन्त्रालय','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Policy, national education information','body_np'=>'नीति, राष्ट्रिय शिक्षा जानकारी','image_url'=>null,'icon'=>'account_balance','link_url'=>'https://moest.gov.np','is_active'=>1],
    ['page_slug'=>'links','section_key'=>'link','sort_order'=>2,'title_en'=>'CEHRD — Center for Education and Human Resource Development','title_np'=>'सीईएचआरडी — शिक्षा तथा मानव स्रोत विकास केन्द्र','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'IEMIS, school education administration','body_np'=>'IEMIS, विद्यालय शिक्षा प्रशासन','image_url'=>null,'icon'=>'school','link_url'=>'https://cehrd.gov.np','is_active'=>1],
    ['page_slug'=>'links','section_key'=>'link','sort_order'=>3,'title_en'=>'National Examinations Board (NEB)','title_np'=>'राष्ट्रिय परीक्षा बोर्ड (एनईबी)','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Grade 11–12 registration, examinations, results','body_np'=>'कक्षा ११–१२ दर्ता, परीक्षा, नतिजा','image_url'=>null,'icon'=>'assignment','link_url'=>'https://neb.gov.np','is_active'=>1],
    ['page_slug'=>'links','section_key'=>'link','sort_order'=>4,'title_en'=>'Curriculum Development Centre (CDC)','title_np'=>'पाठ्यक्रम विकास केन्द्र (सीडीसी)','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Curriculum, textbooks, learning materials','body_np'=>'पाठ्यक्रम, पाठ्यपुस्तक, सिकाइ सामग्री','image_url'=>null,'icon'=>'menu_book','link_url'=>'https://cdc.gov.np','is_active'=>1],
    ['page_slug'=>'links','section_key'=>'link','sort_order'=>5,'title_en'=>'SEE','title_np'=>'एसईई','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Secondary Education Examination','body_np'=>'माध्यमिक शिक्षा परीक्षा','image_url'=>null,'icon'=>'verified','link_url'=>'https://see.gov.np','is_active'=>1],
    ['page_slug'=>'links','section_key'=>'link','sort_order'=>6,'title_en'=>'Malangwa Municipality','title_np'=>'मलंगवा नगरपालिका','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Local government — ward, municipal notices','body_np'=>'स्थानीय सरकार — वडा, नगरपालिका सूचनाहरू','image_url'=>null,'icon'=>'location_city','link_url'=>'https://malangwamun.gov.np','is_active'=>1],
    ['page_slug'=>'links','section_key'=>'link','sort_order'=>7,'title_en'=>'Madhesh Province','title_np'=>'मधेश प्रदेश','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Provincial government','body_np'=>'प्रदेश सरकार','image_url'=>null,'icon'=>'map','link_url'=>'https://madhesh.gov.np','is_active'=>1],
    ['page_slug'=>'links','section_key'=>'link','sort_order'=>8,'title_en'=>'National Education-related Portals','title_np'=>'राष्ट्रिय शिक्षा सम्बन्धी पोर्टलहरू','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Additional references — verify before use','body_np'=>'थप सन्दर्भहरू — प्रयोग गर्नु अघि प्रमाणित गर्नुहोस्','image_url'=>null,'icon'=>'language','link_url'=>'https://www.nea.gov.np','is_active'=>1],
    // science — intro
    ['page_slug'=>'science','section_key'=>'intro','sort_order'=>0,'title_en'=>'What the Science stream is for','title_np'=>'विज्ञान स्ट्रिम केका लागि हो','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>The <strong>+2 Science</strong> program at Shree Public Secondary School is a two-year higher secondary course (Grades 11 and 12) under the <strong>National Examinations Board (NEB)</strong>. It is one of two NEB streams currently offered at the school — the other being <strong>+2 Management</strong>.</p><p>Students who have completed Grade 10 (SEE) from Shree Public or any other recognised institution may apply to Grade 11 in this stream, subject to eligibility criteria and available seats as confirmed each year by the school office.</p><p>Study extends over two academic years with internal assessments and board examinations as required by NEB.</p>','body_np'=>'<p><strong>+२ विज्ञान</strong> कार्यक्रम श्री पब्लिक माध्यमिक विद्यालयमा <strong>राष्ट्रिय परीक्षा बोर्ड (एनईबी)</strong> अन्तर्गतको दुई वर्षे उच्च माध्यमिक पाठ्यक्रम (कक्षा ११ र १२) हो। यो विद्यालयमा हाल सञ्चालित दुई एनईबी स्ट्रिमहरूमध्ये एक हो — अर्को <strong>+२ व्यवस्थापन</strong> हो।</p><p>श्री पब्लिक वा अन्य मान्यता प्राप्त संस्थाबाट कक्षा १० (एसईई) पूरा गरेका विद्यार्थीहरूले यस स्ट्रिममा कक्षा ११ मा आवेदन दिन सक्छन्।</p><p>अध्ययन दुई शैक्षिक वर्षसम्म चल्छ र एनईबीको आवश्यकता अनुसार आन्तरिक मूल्याङ्कन र बोर्ड परीक्षाहरू हुन्छन्।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // science — highlight (4)
    ['page_slug'=>'science','section_key'=>'highlight','sort_order'=>1,'title_en'=>'Scientific reasoning','title_np'=>'वैज्ञानिक तर्क','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Observation, experimentation and interpreting evidence — building habits of inquiry and careful measurement.','body_np'=>'अवलोकन, प्रयोग र प्रमाणको व्याख्या — जिज्ञासा र सावधानीपूर्वक मापनको बानी विकास।','image_url'=>null,'icon'=>'biotech','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'science','section_key'=>'highlight','sort_order'=>2,'title_en'=>'Mathematics','title_np'=>'गणित','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Quantitative reasoning, algebraic and analytical thinking used across science and technology studies.','body_np'=>'विज्ञान र प्रविधि अध्ययनमा प्रयोग हुने परिमाणात्मक तर्क, बीजगणितीय र विश्लेषणात्मक सोच।','image_url'=>null,'icon'=>'calculate','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'science','section_key'=>'highlight','sort_order'=>3,'title_en'=>'Analytical thinking','title_np'=>'विश्लेषणात्मक सोच','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Breaking problems into parts, evaluating data and forming reasoned conclusions.','body_np'=>'समस्यालाई भागमा विभाजन गर्ने, तथ्याङ्क मूल्याङ्कन गर्ने र तर्कसंगत निष्कर्ष निकाल्ने।','image_url'=>null,'icon'=>'psychology','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'science','section_key'=>'highlight','sort_order'=>4,'title_en'=>'Practical understanding & problem solving','title_np'=>'व्यावहारिक बुझाइ र समस्या समाधान','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Applying concepts to real questions — where lab access and practical work are available, students learn through demonstration and supervised activity.','body_np'=>'अवधारणाहरूलाई वास्तविक प्रश्नहरूमा लागू गर्ने — प्रयोगशाला र व्यावहारिक कार्य उपलब्ध हुँदा विद्यार्थीहरूले प्रदर्शन र पर्यवेक्षण गतिविधि मार्फत सिक्छन्।','image_url'=>null,'icon'=>'science','link_url'=>null,'is_active'=>1],
    // management — intro
    ['page_slug'=>'management','section_key'=>'intro','sort_order'=>0,'title_en'=>'What the Management stream is for','title_np'=>'व्यवस्थापन स्ट्रिम केका लागि हो','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'<p>The <strong>+2 Management</strong> program is a two-year higher secondary course (Grades 11 and 12) under the <strong>National Examinations Board (NEB)</strong> — the second NEB stream currently operated at Shree Public alongside <strong>+2 Science</strong>.</p><p>Students who have completed Grade 10 (SEE) from Shree Public or any other recognised institution may apply to Grade 11 in this stream, subject to the eligibility criteria and seats confirmed each year by the school office.</p>','body_np'=>'<p><strong>+२ व्यवस्थापन</strong> कार्यक्रम <strong>राष्ट्रिय परीक्षा बोर्ड (एनईबी)</strong> अन्तर्गतको दुई वर्षे उच्च माध्यमिक पाठ्यक्रम (कक्षा ११ र १२) हो — श्री पब्लिकमा <strong>+२ विज्ञान</strong> सँगै सञ्चालित दोस्रो एनईबी स्ट्रिम।</p><p>श्री पब्लिक वा अन्य मान्यता प्राप्त संस्थाबाट कक्षा १० (एसईई) पूरा गरेका विद्यार्थीहरूले यस स्ट्रिममा कक्षा ११ मा आवेदन दिन सक्छन्।</p>','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
    // management — highlight (4)
    ['page_slug'=>'management','section_key'=>'highlight','sort_order'=>1,'title_en'=>'Business understanding','title_np'=>'व्यापार बुझाइ','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'How businesses are organised, how they operate and how decisions are made — introduced at higher-secondary level.','body_np'=>'व्यवसायहरू कसरी संगठित हुन्छन्, कसरी सञ्चालन हुन्छन् र निर्णयहरू कसरी लिइन्छ — उच्च माध्यमिक तहमा परिचय गराइन्छ।','image_url'=>null,'icon'=>'business_center','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'management','section_key'=>'highlight','sort_order'=>2,'title_en'=>'Accounting concepts','title_np'=>'लेखा अवधारणाहरू','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Recording, classifying and interpreting financial information — the language of business records.','body_np'=>'वित्तीय जानकारीको रेकर्डिङ, वर्गीकरण र व्याख्या — व्यापार रेकर्डको भाषा।','image_url'=>null,'icon'=>'receipt_long','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'management','section_key'=>'highlight','sort_order'=>3,'title_en'=>'Economics','title_np'=>'अर्थशास्त्र','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Scarcity, markets, production and trade — basic economic thinking applied to everyday and business contexts.','body_np'=>'अभाव, बजार, उत्पादन र व्यापार — दैनिक र व्यापार सन्दर्भमा लागू गरिने आधारभूत आर्थिक सोच।','image_url'=>null,'icon'=>'trending_up','link_url'=>null,'is_active'=>1],
    ['page_slug'=>'management','section_key'=>'highlight','sort_order'=>4,'title_en'=>'Organisational thinking, communication & entrepreneurship','title_np'=>'संगठनात्मक सोच, सञ्चार र उद्यमशीलता','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'Planning, organising, working with others, written and spoken communication, and an introduction to starting and running an enterprise.','body_np'=>'योजना, संगठन, अरूसँग मिलेर काम गर्ने, लिखित र मौखिक सञ्चार, र उद्यम सुरु गर्ने र सञ्चालन गर्ने परिचय।','image_url'=>null,'icon'=>'groups','link_url'=>null,'is_active'=>1],
    // publications — intro
    ['page_slug'=>'publications','section_key'=>'intro','sort_order'=>0,'title_en'=>'Official publications for transparency','title_np'=>'पारदर्शिताका लागि आधिकारिक प्रकाशनहरू','subtitle_en'=>null,'subtitle_np'=>null,'body_en'=>'School annual reports, financial summaries (as approved for disclosure), School Improvement Plan (SIP) summaries, prospectus and similar institutional publications. Documents are shown with title, category, publish date and file type.','body_np'=>'विद्यालय वार्षिक प्रतिवेदन, वित्तीय सारांश (प्रकाशनका लागि स्वीकृत), विद्यालय सुधार योजना (SIP) सारांश, prospectus र यस्तै संस्थागत प्रकाशनहरू। कागजातहरू शीर्षक, श्रेणी, प्रकाशन मिति र फाइल प्रकार सहित देखाइन्छ।','image_url'=>null,'icon'=>null,'link_url'=>null,'is_active'=>1],
  ];
}
